
using System;
using XCad.Sw.Annotations;
using XCad.Sw.Geometry;

namespace XCad.Sw.Features.CustomFeature.Structures {
    /// <summary>
    /// Rebuild result of the <see cref="ISwMacroFeature"/>
    /// </summary>
    public class RebuildResult {
        /// <summary>
        /// Creates rebuild result from bodies
        /// </summary>
        /// <param name="bodies">Bodies</param>
        /// <returns>Rebuild result</returns>
        public static BodyRebuildResult FromBodies(params ISwBody[] bodies)
            => new BodyRebuildResult() {
                Bodies = bodies
            };

        /// <summary>
        /// Creates rebuild result from status
        /// </summary>
        /// <param name="result">Result</param>
        /// <param name="errMsg">Error if failed or warning</param>
        /// <returns>Rebuild result</returns>
        public static RebuildResult FromStatus(bool result, string errMsg = "")
            => new RebuildResult() {
                Result = result,
                ErrorMessage = errMsg
            };

        /// <summary>
        /// Status result
        /// </summary>
        public bool Result { get; set; }

        /// <summary>
        /// Error message
        /// </summary>
        public string ErrorMessage { get; set; }

        /// <summary>
        /// Optional delegate to bind generated dimensions using a closure over geometry generation variables.
        /// </summary>
        public Action<string, ISwDimension> AlignDimension { get; set; }
    }

    /// <summary>
    /// Bodies result of the <see cref="ISwMacroFeature"/>
    /// </summary>
    public class BodyRebuildResult : RebuildResult {
        /// <summary>
        /// Bodies generated by macro feature
        /// </summary>
        public ISwBody[] Bodies { get; set; }
    }
}